name: Create Repository from Template

on:
  workflow_dispatch:
    inputs:
      filiera:
        type: choice
        description: Filiera di appartenenza
        options: 
        - corebanking
        - test
      repository-name:
        type: string
        required: true        
        description: Nome del repository       
      api-spec-name:
        type: string
        required: true              
        description: Nome file API Spec
jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Create repository from template
        shell: bash      
        run: |
          gh repo create "antonior0409/test-template5" --template https://github.com/antonior0409/openapi-template --public  --clone        
          echo "gh repo create $ORG/$REPO --template https://github.com/antonior0409/openapi-template --public --clone"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG: ${{ github.event.inputs.filiera }}
          REPO: ${{ github.event.inputs.repository-name }}
          API_SPEC_NAME: ${{ github.event.inputs.api-spec-name }}
